---
- name: Provision the infrastructure
  hosts: localhost
  connection: local
  roles:
  - eduroam-provision

<<<<<<< HEAD


- name: Create the eduroam-hosts group
  hosts: eduroam-host
  connection: docker
  roles:
  - eduroam-configure


`
=======
- name: Create the eduroam-hosts group
  hosts: eduroam-host
  connection: docker
  pre_tasks:
    - setup:
        filter: "*hostname*"
  roles:
  - eduroam-configure
>>>>>>> 44112c5b5f926bac8a97433270f6898988e91553
