---
- name: Provision the infrastructure
  hosts: localhost
  connection: local
  roles:
  - eduroam-provision

# - name: Provision the hosts
#   hosts: eduroam-host
#   roles:
#   - eduroam-configure
